name = "serelix-contact-api"
main = "worker.js"
compatibility_date = "2023-12-01"

[vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1430960028990439546/K1TzTiagrGJcWWBhByvCJn3GZ2pJYm6Z8wd0AkZZn9sw4bvlvaMu7Dqcsp8tUF0fPKwv"