name: Deploy to NAS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Rsync and rebuild
        run: |
          rsync -az --delete ./ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/mnt/data_pool_b/xzhiyouu/Projects/serelix-studio-crafted/
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd /mnt/data_pool_b/xzhiyouu/Projects/serelix-studio-crafted && \
            docker-compose up --build -d
          "
